#ifndef UNIVERSE_CONSTANTS_H_
#define UNIVERSE_CONSTANTS_H_

#define		WORLD_SIZE_MULTIPLIER		10.0f
#define		WORLD_TOTAL_MASS			300000.0f
#define		PARTICLES_MAX_COUNT			5000
#define		PARTICLE_BASE_MASS			50.0f
#define		PARTICLE_EXPLODE_MASS		10000.0f
#define		SIMULATION_DELTA			0.1f

#define		GRAVITY_VALUE				300000.0f
#define		DECELERATION_VALUE			0.01f
#define		MASS_LEAKAGE_VALUE			0.00001f
#define		TEMP_RADIATION_VALUE		0.01f
#define		TEMP_MAX_VALUE				100.0f

#define		ACCURACY_THETA				1.0f
//#define		USE_PARALLEL_FOR

#endif /* UNIVERSE_CONSTANTS_H_ */
